kind = "web"
previewPath = "/"
title = "NexoraAI"
version = "1.0.0"
id = "artifacts/nexora-web"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 21711

[services.development]
run = "pnpm --filter @workspace/nexora-web run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/nexora-web", "run", "build" ]
publicDir = "artifacts/nexora-web/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "21711"
BASE_PATH = "/"
